# Generated by Django 3.2.10 on 2023-04-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='latestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
                ('userName', models.CharField(max_length=50)),
                ('userProfile', models.CharField(max_length=100)),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('desc', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
